// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/StanislavStefanov/Battleships/utils"
	websocket "github.com/gorilla/websocket"
	mock "github.com/stretchr/testify/mock"
)

// ResponseSender is an autogenerated mock type for the ResponseSender type
type ResponseSender struct {
	mock.Mock
}

// SendResponse provides a mock function with given fields: response, conn
func (_m *ResponseSender) SendResponse(response utils.Response, conn *websocket.Conn) {
	_m.Called(response, conn)
}
