// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	utils "github.com/StanislavStefanov/Battleships/pkg/web"
	player "github.com/StanislavStefanov/Battleships/server/player"
	mock "github.com/stretchr/testify/mock"
)

// ResponseSender is an autogenerated mock type for the ResponseSender type
type ResponseSender struct {
	mock.Mock
}

// SendResponse provides a mock function with given fields: response, conn
func (_m *ResponseSender) SendResponse(response utils.Response, conn player.Connection) {
	_m.Called(response, conn)
}
